//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Учетные_записи> Учетные_записи { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Вопросы> Вопросы { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Ответы> Ответы { get; set; }
        public virtual DbSet<Подразделение> Подразделение { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Разделы> Разделы { get; set; }
        public virtual DbSet<Результат_теста> Результат_теста { get; set; }
        public virtual DbSet<Тесты> Тесты { get; set; }
    }
}
