//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вопросы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вопросы()
        {
            this.Ответы = new HashSet<Ответы>();
        }
    
        public int id_вопроса { get; set; }
        public int id_Теста { get; set; }
        public string Текст_вопроса { get; set; }
        public string Тип_ответа { get; set; }
        public Nullable<int> Номер_подвопроса { get; set; }
    
        public virtual Тесты Тесты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ответы> Ответы { get; set; }
    }
}
