//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Учетные_записи
    {
        public int id { get; set; }
        public string Имя_учетной_записи { get; set; }
        [StringLength(15, ErrorMessage = "Длина пароля не более 15 символов")]
        public string Пароль { get; set; }
    }
}
